name: Terraform BigQuery Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Apply Terraform to GCP
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
      TF_VAR_credentials_file: ${{ github.workspace }}/gcp-key.json

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Write GCP credentials file
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > gcp-key.json

      - name: list contents
        run: ls

      - name: Terraform Init
        run: terraform -chdir=terraform-bigquery init -migrate-state

      - name: Terraform Plan
        run: terraform -chdir=terraform-bigquery plan -input=false

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform -chdir=terraform-bigquery apply -auto-approve -input=false